---
# tasks file for learnCoditionals
- name: Learn how to use conditionals in ansible
  command: echo "Srini-> {{ item }}">>/tmp/srini
  loop: [0,2,4,6,8,10]
  when: item > 6
  delegate_to: localhost

